pipeline {
    agent {
  label 'linux'
}

    tools {
        // Make sure Maven is configured in Jenkins with the correct name, like 'Maven 3.6.3'
        maven 'Maven 3.6.3'
    }

    stages {
        stage('install') {
            steps {
                sh 'mvn clean install'
            }
            post {
  success {
   archiveArtifacts artifacts :'**/target/*.war'
}
        }

        
    }
}
