pipeline{
    agent {label 'agent-server'}
    tools{
        maven 'mymaven'
    }
    stages{
        stage('clean'){
            steps{
                sh 'mvn clean install'
            }
        }
        stage('test'){
            steps{
                sh 'mvn test'
            }
        }
        stage('deploy'){
            steps{
                script{
                if(FileExists('deploy.sh')){
                sh './deploy.sh'
                }
                else{
                    echo "there is no file"
                }
            }
        }
    }
}
}
